// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProveedoresEY.Models;

#nullable disable

namespace ProveedoresEY.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProveedoresEY.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FacturacionAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaUltimaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificacionTributaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefonico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitioWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorreoElectronico = "contact@britenterprises.com",
                            DireccionFisica = "123 Main St, London, UK",
                            FacturacionAnual = 5000000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1586),
                            IdentificacionTributaria = "123456789",
                            NombreComercial = "Brit Enterprises",
                            NumeroTelefonico = "1234567890",
                            Pais = "United Kingdom",
                            RazonSocial = "BRIT ENTERPRISES CORP.",
                            SitioWeb = "http://www.britenterprises.com"
                        },
                        new
                        {
                            Id = 2,
                            CorreoElectronico = "info@britsky.com",
                            DireccionFisica = "456 High St, New York, USA",
                            FacturacionAnual = 10000000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1596),
                            IdentificacionTributaria = "234567890",
                            NombreComercial = "Brit Sky",
                            NumeroTelefonico = "2345678901",
                            Pais = "United States",
                            RazonSocial = "BRIT SKY SERVICES INC.",
                            SitioWeb = "http://www.britsky.com"
                        },
                        new
                        {
                            Id = 3,
                            CorreoElectronico = "support@midweek.com",
                            DireccionFisica = "789 Park Ave, Paris, France",
                            FacturacionAnual = 7500000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1627),
                            IdentificacionTributaria = "345678901",
                            NombreComercial = "Midweek",
                            NumeroTelefonico = "3456789012",
                            Pais = "France",
                            RazonSocial = "MIDWEEK LTD.",
                            SitioWeb = "http://www.midweek.com"
                        },
                        new
                        {
                            Id = 4,
                            CorreoElectronico = "sales@kinsleyimpex.com",
                            DireccionFisica = "123 Trade St, Tokyo, Japan",
                            FacturacionAnual = 6000000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1629),
                            IdentificacionTributaria = "456789012",
                            NombreComercial = "Kinsley Impex",
                            NumeroTelefonico = "4567890123",
                            Pais = "Japan",
                            RazonSocial = "KINSLEY IMPEX LIMITED",
                            SitioWeb = "http://www.kinsleyimpex.com"
                        },
                        new
                        {
                            Id = 5,
                            CorreoElectronico = "contact@zarazen.com",
                            DireccionFisica = "456 Market St, Berlin, Germany",
                            FacturacionAnual = 8500000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1630),
                            IdentificacionTributaria = "567890123",
                            NombreComercial = "Zarazen",
                            NumeroTelefonico = "5678901234",
                            Pais = "Germany",
                            RazonSocial = "ZARAZEN S.A.",
                            SitioWeb = "http://www.zarazen.com"
                        },
                        new
                        {
                            Id = 6,
                            CorreoElectronico = "info@mrholiday.com",
                            DireccionFisica = "789 Vacation Rd, Sydney, Australia",
                            FacturacionAnual = 3000000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1632),
                            IdentificacionTributaria = "678901234",
                            NombreComercial = "Mr. Holiday",
                            NumeroTelefonico = "6789012345",
                            Pais = "Australia",
                            RazonSocial = "MR. HOLIDAY LIMITED",
                            SitioWeb = "http://www.mrholiday.com"
                        },
                        new
                        {
                            Id = 7,
                            CorreoElectronico = "membership@highfliersclub.com",
                            DireccionFisica = "123 Luxury Ln, Dubai, UAE",
                            FacturacionAnual = 9500000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1634),
                            IdentificacionTributaria = "789012345",
                            NombreComercial = "Highfliers Club",
                            NumeroTelefonico = "7890123456",
                            Pais = "United Arab Emirates",
                            RazonSocial = "THE HIGHFLIERS CLUB LIMITED",
                            SitioWeb = "http://www.highfliersclub.com"
                        },
                        new
                        {
                            Id = 8,
                            CorreoElectronico = "service@alluckindustrial.com",
                            DireccionFisica = "456 Manufacturing St, Seoul, South Korea",
                            FacturacionAnual = 50000000m,
                            FechaUltimaEdicion = new DateTime(2024, 8, 2, 2, 26, 41, 132, DateTimeKind.Local).AddTicks(1635),
                            IdentificacionTributaria = "890123456",
                            NombreComercial = "Alluck Industrial",
                            NumeroTelefonico = "8901234567",
                            Pais = "South Korea",
                            RazonSocial = "ALLUCK INDUSTRIAL LTD.",
                            SitioWeb = "http://www.alluckindustrial.com"
                        });
                });

            modelBuilder.Entity("ProveedoresEY.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            User = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "user123",
                            User = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
